# Generated by Django 4.2.7 on 2023-12-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(upload_to='static/producto/img/'),
        ),
    ]
